### ISSUE TITLE
.env questions

### ISSUE THREAD

**Issue by rkanka21** [azusapacificuniversity/lti-gmeet#1]
Hello, I have deployed canvas on AWS and its working great for last 6 months. I saw that Instructure released a Google Meet LTI, but thinking its only for paid users, not open source, so I was so glad to find this.  C

Can you please explain in a little more detail how to get the data for the fields in the .env file?

**Comment by enov** [comment]
Hi @rkanka21 Thank you for your interest!

You have to create a database and run the CREATE sql that is available in https://github.com/azusapacificuniversity/lti-gmeet/blob/master/sql/create_table.sql . Please note, that CREATE SQL is written in a MySQL/MariaDB dialect. However, the project makes use of knex. So, having the corresponding table in another database still would work.

- DB_HOST= Your DB hostname (we do not support custom ports yet)
- DB_NAME= Your Database/Schema name
- DB_USER= Username
- DB_PASS= Password 
- DB_TYPE= knex supported types and dialects

The following "GCAL_" prefix env vars you need to get them from https://console.developers.google.com/ by creating an oAuth project and credentials in there (I am sorry about the vagueness here, as I do not recall all the steps we took to have those)

- GCAL_CALENDAR_USER: The email you used to log in into the console
- GCAL_SERVICE_ACCOUNT: The service account, in the form of `org-service@org-service.iam.gserviceaccount.com`
- GCAL_PRIVATE_KEY: `-----BEGIN PRIVATE KEY-----\nyadadaydadyaydaydadyaya\n\n-----END PRIVATE KEY-----`
- GCAL_CALENDAR_ID: ID of the Google Calendar you created for this purpose, that is accessible by everyone in your org. In the form of `org.edu_yadayadaydadyadyadyada@group.calendar.google.com`
- GCAL_OAUTH_CLIENT_ID: Oauth Client ID in the form of `yadayada-yadayadayada.apps.googleusercontent.com`
- GCAL_OAUTH_CLIENT_SECRET: `yadayadayadaydadya-yadayadaydada`
- GCAL_OAUTH_REDIRECT_URL: https://this-app-hostname.org.edu/api/v1/oauthcallback

There are a couple of other env vars unfortunately not mentioned in the `sample.env` file. Some of those are shared between your installation of this application and your custom LTI in Canvas that you need to setup using https://github.com/azusapacificuniversity/lti-gmeet/blob/master/src/main/lti-config.xml 

- HOSTNAME: your app's hostname
- OAUTH_CONSUMER_KEY: Oauth1 consumer key shared between your app and your LTI in Canvas installation
- OAUTH_CONSUMER_SECRET: Oauth1 secret shared between your app and your LTI in Canvas
- SESSION_SECRET: A random secret used for Express.js sessions

Congrats if you make it all the way through :sweat_smile: ! If you are able to setup a fully running application we appreciate your time creating a pull request or a wiki page documenting your steps.

Thank you again!

**Comment by enov** [comment]
Hi @rkanka21 , I was wondering about your progress and if you need any more help.

Cheers!

**Comment by enov** [comment]
We're archiving this repository.
